                                                                        url                                                                        |                                                                                       title                                                                                       
---------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 https://www.sciencedaily.com/releases/2018/03/180322181338.htm                                                                                    | Using light to turn yeast into biochemical factories
 https://www.usmagazine.com/entertainment/news/roseanne-slammed-for-mocking-fresh-off-the-boat-black-ish/                                          | ‘Roseanne’ Slammed for Mocking ‘Fresh Off the Boat,’ ‘Black-ish’
 https://www.sciencedaily.com/releases/2018/04/180405093238.htm                                                                                    | Prehistoric reptile pregnant with octuplets
 https://www.sciencedaily.com/releases/2018/04/180405093238.htm                                                                                    | Prehistoric reptile pregnant with octuplets
 https://www.usmagazine.com/entertainment/news/roseanne-slammed-for-mocking-fresh-off-the-boat-black-ish/                                          | ‘Roseanne’ Slammed for Mocking ‘Fresh Off the Boat,’ ‘Black-ish’
 https://www.sciencedaily.com/releases/2018/03/180322181338.htm                                                                                    | Using light to turn yeast into biochemical factories
 https://www.sciencedaily.com/releases/2018/04/180405093238.htm                                                                                    | Prehistoric reptile pregnant with octuplets
 https://www.usmagazine.com/entertainment/news/roseanne-slammed-for-mocking-fresh-off-the-boat-black-ish/                                          | ‘Roseanne’ Slammed for Mocking ‘Fresh Off the Boat,’ ‘Black-ish’
 https://www.livescience.com/g00/33816-quantum-mechanics-explanation.html                                                                          | What Is Quantum Mechanics?
 https://www.livescience.com/g00/33816-quantum-mechanics-explanation.html                                                                          | What Is Quantum Mechanics?
 https://www.sciencedaily.com/releases/2018/04/180404133532.htm                                                                                    | Tens of thousands of black holes may exist in Milky Way's center
 http://spacenews.com/rocket-lab-sets-date-for-first-commercial-launch/                                                                            | Rocket Lab sets date for first commercial launch - SpaceNews.com
 https://www.youtube.com/watch?v=AhFjfCdG61Y                                                                                                       | Pythagorean Theorem
 https://www.scientificamerican.com/article/beijing-launches-pioneering-brain-science-center/                                                      | Beijing Launches Pioneering Brain-Science Center
 https://www.sciencenews.org/article/flying-insects-tell-tales-long-distance-migrations                                                            | Flying insects tell tales of long-distance migrations
 https://www.sciencedaily.com/releases/2018/03/180322112731.htm                                                                                    | Design approach developed for important new catalysts for energy conversion and storage: New method could aid in design of pharmaceuticals and optical and data storage materials
 https://www.youtube.com/watch?v=rJesac0_Ftw                                                                                                       | JSON and AJAX Tutorial: With Real Examples
 https://www.youtube.com/watch?v=TG6zOECUpm4                                                                                                       | 2.1 Skill: Drawing molecular diagrams
 https://www.youtube.com/watch?v=rCWOdfQ3cwQ                                                                                                       | Definite Integral Calculus Examples, Integration - Basic Introduction, Practice Problems
 https://www.youtube.com/watch?v=0fKg7e37bQE&t=32s                                                                                                 | Github Tutorial For Beginners - Github Basics for Mac or Windows & Source Control Basics
 https://www.youtube.com/watch?v=I-66U_8l37c                                                                                                       | Stock Market For Beginners 📈 TRADING AND INVESTING 101
 https://www.youtube.com/watch?v=F3QpgXBtDeo                                                                                                       | How The Stock Exchange Works (For Dummies)
 https://animagraffs.com/how-a-car-engine-works/                                                                                                   | How a Car Engine Works - Animagraffs
 https://www.codecademy.com/                                                                                                                       | Codecademy - learn to code, interactively, for free
 https://www.khanacademy.org/                                                                                                                      | Khan Academy
 https://www.art-is-fun.com/how-to-use-pastels/                                                                                                    | How to Use Pastels: Learn Various Pastel Painting Techniques in this Pastel Painting Workshop!
 https://www.youtube.com/watch?v=dpF_zAiLpvU                                                                                                       | How to Use Pastels For Beginners
 https://www.youtube.com/watch?v=TntR8sb-UMc                                                                                                       | Drawing 101 - Simplify Your Drawings
 https://www.youtube.com/watch?v=x4zz2yH1bLE                                                                                                       | Rainbow Willow Tree Q Tip Acrylic Painting for Beginners tutorial 🌈🎨💜
 https://www.youtube.com/watch?v=nKeqyB8G3TY                                                                                                       | How to paint a tree in Acrylic lesson 6
 https://www.youtube.com/watch?v=yqRT2urNPgE                                                                                                       | Midnight Raven Acrylic Step by Step Painting on Canvas for Beginners
 https://www.chemistryworld.com/news/iron-rich-rock-helps-oceans-sink-atmospheric-carbon/3008858.article                                           | Iron-rich rock helps oceans sink atmospheric carbon
 https://www.scientificamerican.com/article/a-noble-gas-surprise-helium-can-form-weird-compounds/                                                  | A Noble Gas Surprise: Helium Can Form Weird Compounds
 https://www.scientificamerican.com/article/stronger-than-steel-able-to-stop-a-speeding-bullet-mdash-it-rsquo-s-super-wood/                        | Stronger Than Steel, Able to Stop a Speeding Bullet--It's Super Wood!
 https://www.scientificamerican.com/article/chemistry-may-yield-lucrative-use-for-wasted-methane/                                                  | Chemistry May Yield Lucrative Use for Wasted Methane
 https://www.scientificamerican.com/article/scientists-move-closer-to-a-universal-flu-vaccine/                                                     | Scientists Move Closer to a Universal Flu Vaccine
 https://www.nytimes.com/2017/10/07/opinion/sunday/who-invented-zero.html?rref=collection%2Ftimestopic%2FMathematics                               | Opinion | Who Invented ‘Zero’?
 https://www.nytimes.com/2017/04/15/opinion/sunday/the-worlds-most-beautiful-mathematical-equation.html?rref=collection%2Ftimestopic%2FMathematics | Opinion | The World’s Most Beautiful Mathematical Equation
 https://www.nytimes.com/2016/02/28/opinion/sunday/the-wrong-way-to-teach-math.html?rref=collection%2Ftimestopic%2FMathematics                     | Opinion | The Wrong Way to Teach Math
 https://www.youtube.com/watch?v=KdQi3Q1teZU                                                                                                       | Volume Of A Cylinder: How to find THE EASY WAY!
 https://www.youtube.com/watch?v=YECQ5JGNKIc                                                                                                       | Measuring Volume by Counting Unit Cubes
 http://www.statisticshowto.com/probability-and-statistics/probability-main-index/                                                                 | Probability Introduction: Articles and Videos with Solutions!
 https://nrich.maths.org/9649                                                                                                                      | No Title
 http://blogs.discovermagazine.com/d-brief/2018/02/23/diamond-anvils-chemistry/#.WspMr3UbNhE                                                       | Chemists Forge Custom Molecules Upon 'Diamond Anvils' - D-brief
 https://www.sciencedaily.com/releases/2018/03/180330145340.htm                                                                                    | Engineers turn plastic insulator into heat conductor: Technique could prevent overheating of laptops, mobile phones, and other electronics
 https://www.sciencedaily.com/releases/2018/03/180329141017.htm                                                                                    | Sugar-coated nanosheets developed to selectively target pathogens: Molecular foundry-designed 2-D sheets mimic the surface of cells
 https://www.sciencedaily.com/releases/2018/03/180329141017.htm                                                                                    | Sugar-coated nanosheets developed to selectively target pathogens: Molecular foundry-designed 2-D sheets mimic the surface of cells
 https://www.sciencedaily.com/releases/2018/03/180329141017.htm                                                                                    | Sugar-coated nanosheets developed to selectively target pathogens: Molecular foundry-designed 2-D sheets mimic the surface of cells
 https://www.sciencedaily.com/releases/2018/03/180328120053.htm                                                                                    | Next-gen lithium-metal batteries for electric vehicles, smart grids
 https://www.sciencedaily.com/releases/2018/03/180326110150.htm                                                                                    | A new way to find better battery materials: Design principles could point to better electrolytes for next-generation lithium batteries
 https://www.sciencedaily.com/releases/2018/03/180321141348.htm                                                                                    | World's first continuous room-temperature solid-state maser built using diamond
 https://www.sciencedaily.com/releases/2018/03/180320084357.htm                                                                                    | Tiny gels sop up intestinal toxins
 https://www.sciencedaily.com/releases/2018/03/180319144552.htm                                                                                    | Modified biomaterials self-assemble on temperature cues: Precisely ordered biomaterials could be used for drug delivery, tissue engineering and wound-healing
 https://www.sciencedaily.com/releases/2018/03/180314092258.htm                                                                                    | Removing heavy metals from water in a matter of seconds
 https://www.sciencedaily.com/releases/2018/03/180313101729.htm                                                                                    | Ash from dinosaur-era volcanoes linked with shale oil, gas: Shale oil, gas deposits accompany ash layers from thousands of volcanic eruptions
 https://www.sciencedaily.com/releases/2018/03/180308085547.htm                                                                                    | Self-driving robots collect water samples to create snapshots of ocean microbes
 https://www.youtube.com/watch?v=5XjhO9Q2KKQ                                                                                                       | A Brief Introduction to Drawing Molecules
 https://www.youtube.com/watch?v=5tgFEYDNQZs                                                                                                       | How to draw a fischer projection of a molecule
 https://www.youtube.com/watch?v=BEonOqVAC30                                                                                                       | Learn to draw the structure of Glucose Molecule
 https://www.youtube.com/watch?v=4jISjQvdyhs                                                                                                       | Balancing Chemical Equations for beginners
 https://www.youtube.com/watch?v=bSlqA8nedGQ                                                                                                       | How To Balance Equations - Part 1 | Chemistry for All | FuseSchool
 https://www.youtube.com/watch?v=qCLmR9-YY7o                                                                                                       | Meiosis: Where the Sex Starts - Crash Course Biology #13
 https://www.youtube.com/watch?v=URUJD5NEXC8                                                                                                       | Biology: Cell Structure
 https://www.youtube.com/watch?v=sQK3Yr4Sc_k                                                                                                       | Photosynthesis: Crash Course Biology #8
 https://www.youtube.com/watch?v=9fxm85Fy4sQ                                                                                                       | Circulatory & Respiratory Systems - CrashCourse Biology #27
 https://www.youtube.com/watch?v=X9ZZ6tcxArI                                                                                                       | The Heart, part 1 - Under Pressure: Crash Course A&P #25
 https://www.youtube.com/watch?v=X9ZZ6tcxArI                                                                                                       | The Heart, part 1 - Under Pressure: Crash Course A&P #25
 https://www.youtube.com/watch?v=v43ej5lCeBo                                                                                                       | Blood Vessels, part 1 - Form and Function: Crash Course A&P #27
 https://www.britannica.com/science/polymerization                                                                                                 | Polymerization | chemical reaction
 https://www.britannica.com/science/hydrate                                                                                                        | Hydrate | chemical compound
 https://www.britannica.com/science/oxide                                                                                                          | Oxide | chemical compound
 https://www.britannica.com/science/metal-chemistry                                                                                                | Metal | chemistry
 https://www.britannica.com/science/condensed-matter-physics                                                                                       | Condensed-matter physics
 https://www.sciencedaily.com/releases/2018/03/180328143247.htm                                                                                    | Latest nanowire experiment boosts confidence in Majorana sighting: New test matches theory and offers the best evidence yet for the oddball particles
 https://www.sciencedaily.com/releases/2018/03/180327110457.htm                                                                                    | Molecular prison forces diatomic inmates to cell floor: Organic prison too crowded for molecular inmates to move about freely
 https://www.sciencedaily.com/releases/2018/03/180327141726.htm                                                                                    | The future of photonics using quantum dots: Quantum-dot lasers are promising for integrated photonic circuits
 https://www.ted.com/playlists/499/talks_for_the_fiber_arts_lover                                                                                  | 6 TED Talks for the fiber arts lover
 https://www.sciencedaily.com/releases/2018/03/180326140232.htm                                                                                    | Underground neutrino experiment sets the stage for deep discovery about matter
 https://www.sciencedaily.com/releases/2018/03/180319124252.htm                                                                                    | A new kind of quantum bits in two dimensions: Combining two ultra-thin material layers yields new possibilities for quantum electronics
 https://www.youtube.com/watch?v=_GaylSuAB90                                                                                                       | What is Einstein’s general theory of relativity?
 https://www.youtube.com/watch?v=30KfPtHec4s                                                                                                       | Einstein's Theory Of Relativity Made Easy
 https://www.youtube.com/watch?v=4N4fvwW6MCc                                                                                                       | CERN restart 2018: Live from the LHC tunnel
 https://www.youtube.com/watch?v=328pw5Taeg0                                                                                                       | Inside The World's Largest Particle Accelerator
 https://www.youtube.com/watch?v=0nCW7K9DWSY                                                                                                       | CERN Large Hadron Collider LHC, How Does it work? - NOVA Documentary
 https://www.youtube.com/watch?v=FLrEghnKncA                                                                                                       | Large Hadron Collider - Animation Video
 https://www.youtube.com/watch?v=6E2UFAy_FxQ                                                                                                       | Is There Really a Chance that the Large Hadron Collider Could Destroy the Planet?
 https://www.youtube.com/watch?v=6E2UFAy_FxQ                                                                                                       | Is There Really a Chance that the Large Hadron Collider Could Destroy the Planet?
 https://www.youtube.com/watch?v=AInCqm5nCzw                                                                                                       | Special Relativity: Crash Course Physics #42
 https://www.youtube.com/watch?v=ev9zrt__lec                                                                                                       | Albert Einstein's Theory of Relativity
 https://www.youtube.com/watch?v=3ez10ADR_gM                                                                                                       | Intro to Economics: Crash Course Econ #1
 https://www.sciencedaily.com/news/science_society/economics/                                                                                      | Economics News
 https://www.youtube.com/watch?v=NI9TLDIPVcs                                                                                                       | Specialization and Trade: Crash Course Economics #2
 https://www.youtube.com/watch?v=h97fXhDN5qE                                                                                                       | Elon Musk's Basic Economics
 https://www.youtube.com/watch?v=dqxQ3E1bubI                                                                                                       | Behavioral Economics: Crash Course Economics #27
 https://www.ted.com/talks/philip_evans_how_data_will_transform_business                                                                           | How data will transform business
 https://www.sciencedaily.com/releases/2017/10/171025141124.htm                                                                                    | Investing in conservation pays off, study finds
 https://www.ted.com/playlists/272/understanding_world_economics                                                                                   | 9 TED Talks to help you understand world economics
 https://www.ted.com/playlists/306/how_to_spend_your_money                                                                                         | 7 TED Talks on how to spend your money
 https://www.ted.com/playlists/73/the_global_power_shift                                                                                           | The global power shift
 https://www.ted.com/talks/janet_echelman?referrer=playlist-talks_for_the_fiber_arts_lover                                                         | Taking imagination seriously
 https://www.youtube.com/watch?v=-9o51nS-wuk                                                                                                       | STOCK MARKET FOR DUMMIES 📈 How The Stock Market Works
(101 rows)

